### ISSUE TITLE
Design DB schema

### ISSUE THREAD

**Issue by SebastianJames55** [SebastianJames55/mind-reader#1]
Please refer to the [snoop-stein example](http://docs.mindsdb.com/sql/tutorials/twitter-chatbot#5-setting-up-a-database) & beyond to design the schema. Let me know if we have to discuss any points.

**Comment by Payne680** [comment]
Please I can't access the link.

**Comment by SebastianJames55** [comment]
As ```http://``` wasn't included in the prefix of the url, our project repo link was prepended. I have updated, can you check?

**Comment by Payne680** [comment]
Yes. It's working now

**Comment by SebastianJames55** [comment]
In reference to [snoop-stein example of setting up DB](https://docs.mindsdb.com/sql/tutorials/twitter-chatbot#5-setting-up-a-database), input & output tables will help keep track of the conversation. 

The initial idea in the case of a happy flow for mind-reader: 
The user would be giving a manual input within a minute (the idea is to have job running every minute) and text would be limited such that it can be handled in-memory. Concluding that we require just the single input table. 

Cases to handle: 
- massive text input from user trying to crash the system

The input collected over a minute can be inserted into table as a single DB query rather than each input being put into table which would lead to multiple DB queries. 

Points to take care:
- Based on the input data finetune the model
- Need to think of how to get a single reply or a set of replies based on the context of the input texts

The reply of the model based on the input will be put into output table.

**Comment by SebastianJames55** [comment]
Input table
```
CREATE TABLE chatbot_input (
  id text CHARACTER SET utf8mb4,
  created_at text CHARACTER SET utf8mb4,
  "text" text CHARACTER SET utf8mb4
  );
```

Output table
```
CREATE TABLE chatbot_output (
  id text CHARACTER SET utf8mb4,
  created_at text CHARACTER SET utf8mb4,
  "text" text CHARACTER SET utf8mb4
  );
```

**Comment by SebastianJames55** [comment]
Initial analysis completed. As per understanding during implementation the schema would be modified.
